### ISSUE TITLE
naturalvoices voice packs ahk

### ISSUE THREAD

**Issue by Zedroid** [lesleyrs/clipboard-narrator#2]
could you please add the naturalvoices voice packs from jenny, guy or aria in win11 22h2 like this guy did for his autohotkey script in edge

https://www.autohotkey.com/boards/viewtopic.php?t=97450 

I cannot select as voice packs in system settings winRT API even in the terminal version, so I understand if that might be a bit more complicated
https://github.com/lesleyrs/tts-tui
It is only available in Narrator

**Comment by lesleyrs** [comment]
I can't actually test this right now as I'm on windows 10 not 11.

Based on google results it shows you can select "add natural voices" in windows settings and then you can select the voice in the same settings menu. Just by doing that should make it work in `tts-tui` unless Micro$oft is doing something to prevent that.

**Comment by lesleyrs** [comment]
Unfortunately you can't use natural voices outside of Narrator for now. Edge is different because they are online voices so they aren't stored locally.
