### ISSUE TITLE
Optionally skip reading out superscripts. 

### ISSUE THREAD

**Issue by domi-domi** [lesleyrs/clipboard-narrator#3]
Reading out superscript numbers as "footnote 1," "footnote 2," etc can be helpful, but likely in very limited cases. It would be nice if there was either an option to toggle superscript reading off specifically, or overall a verbosity setting which could go from how the app reads now (most verbose) to where the app only reads words and lead numbers (least verbose). The superscripts could even be replaced with a ping sound in background, or similar, which acknowledges the presence of a note, without interrupting the reading. 

I've found sometimes stylizing things like first as "1st" will make the app read "one-S.-T." or similar. In those cases, the flow of the reading could be less interrupted even if the app just read it as "One" and ignored the tail characters after the one. This one might require further investigation, but the superscripts are definitely skippable/replaceable.

**Comment by lesleyrs** [comment]
Sorry, I won't be doing this as I'm busy working on other projects now. I myself am using https://github.com/lesleyrs/tts-tui right now (also unmaintained but it works well on Windows). When I let tts-tui read `1st` it will pronounce it correctly as it uses the newer winrt speech api.

About your first problem, I just try to avoid copying too much at once and it hasn't been much of an issue.
